baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'Charles Bricout'



[markup.goldmark.renderer]
unsafe = true

[params]
image_folder = "images"
image_ext = "webp"
dateFormat = "02/01/06"
math =true

[taxonomies]
tag = 'blog/tags'


[markup]
  [markup.highlight]
    LineNos=true
    style="catppuccin-latte"
   [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]